@opencode_oai_HostAddress = http://localhost:5118

GET {{opencode_oai_HostAddress}}/todos/
Accept: application/json

###

GET {{opencode_oai_HostAddress}}/todos/1
Accept: application/json

###
